1737051245911	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=schedule)
1737052952154	Sync.SyncScheduler	DEBUG	Network link status changed to "down". Offline?: false
1737052952154	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1737052952154	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=schedule)
1737052952157	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1737052952171	Sync.SyncScheduler	DEBUG	Woke from sleep.
1737052952172	Sync.SyncScheduler	DEBUG	Online, will sync in 2s.
1737052952172	Sync.SyncScheduler	DEBUG	Next sync in 2000 ms. (why=wake_notification)
1737052952173	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1737052954174	Sync.Service	DEBUG	User-Agent: Firefox/134.0.1 (Linux x86_64) FxSync/1.136.0.20250113214611.desktop
1737052954174	Sync.Service	INFO	Starting sync at 2025-01-16 13:42:34 in browser session o0thTJmpnxKt
1737052954174	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1737052954176	Sync.Status	INFO	Resetting Status.
1737052954177	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1737052954177	FirefoxAccounts	DEBUG	FxAccountsProfileClient: Requested profile
1737052954177	FirefoxAccounts	DEBUG	getOAuthToken enter
1737052954178	FirefoxAccounts	TRACE	getCachedToken returning cached token
1737052954178	FirefoxAccounts	DEBUG	getOAuthToken returning a cached token
1737052954178	Services.Common.RESTRequest	DEBUG	GET request to https://profile.accounts.firefox.com/v1/profile
1737052954186	Services.Common.RESTRequest	DEBUG	GET https://profile.accounts.firefox.com/v1/profile failed: 2152398878 - NS_ERROR_UNKNOWN_HOST
1737052954186	FirefoxAccounts	ERROR	Background refresh of profile failed: {"name":"FxAccountsProfileClientError","code":null,"errno":998,"error":"NETWORK_ERROR","message":"[Exception... \"NS_ERROR_UNKNOWN_HOST\"  nsresult: \"0x804b001e (NS_ERROR_UNKNOWN_HOST)\"  location: \"JS frame :: resource://services-common/rest.sys.mjs :: onStopRequest :: line 478\"  data: no]"}
1737052954187	Sync.Resource	WARN	GET request to https://sync-1-us-west1-g.sync.services.mozilla.com/1.5/162033258/info/collections failed: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1737052954187	Sync.Status	DEBUG	Status.sync: success.sync => error.login.reason.network
1737052954187	Sync.Status	DEBUG	Status.service: success.status_ok => error.sync.failed
1737052954187	Sync.ErrorHandler	ERROR	Sync encountered an error: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1737052954187	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=reschedule)
1737052954189	Sync.Service	DEBUG	Exception calling anonymous function: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
